import { ImageProject, IMAGE_FORMAT_PRESETS } from '../types/imageStudio';
import { defaultMotionBrandTokens } from '../../packages/video-studio/src/motion-kit';

export const INITIAL_IMAGE_TEMPLATES: ImageProject[] = [
  // 🎓 1. DISEÑO OFICIAL POST BLOG (INSTAGRAM 4:5)
  {
    id: 'template-student-visa-instagram',
    title: 'Guía Blog: Requisitos Visado Estudiante (4:5)',
    preset: IMAGE_FORMAT_PRESETS[0], // 4:5 (1080x1350)
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 16%, rgba(0, 95, 115, 0.8) 0%, #001219 84%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-badge-hook',
        type: 'block',
        blockType: 'HookAlertBadge',
        title: 'Insignia Guía Oficial 2026',
        position: { x: 50, y: 9 },
        zIndex: 10,
        scale: 1,
        width: 340,
        height: 40,
        props: {
          badge: 'GUÍA OFICIAL 2026 · EXTRANJERÍA',
          pulseColor: '#94D2BD',
        },
      },
      {
        id: 'layer-headline-title',
        type: 'text',
        title: 'Titular Principal',
        position: { x: 50, y: 20 },
        zIndex: 12,
        scale: 1,
        width: 880,
        props: {
          text: 'Seguro Médico Obligatorio para Visado de Estudiante',
          tag: 'h1',
          fontWeight: '800',
          fontSize: 34,
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1.25,
        },
      },
      {
        id: 'layer-illustration-student',
        type: 'block',
        blockType: 'WebIllustration',
        title: 'Ilustración Estudiante & Visado',
        position: { x: 50, y: 44 },
        zIndex: 15,
        scale: 1,
        width: 380,
        height: 270,
        props: {
          illustrationId: 'student',
          title: 'Estudiantes & Visados',
          colorPrimary: '#005F73',
          colorPastel: '#94D2BD',
          colorSecondary: '#FFFFFF',
          colorAccent: '#EE9B00',
          colorNeutral: '#1e293b',
        },
      },
      {
        id: 'layer-glass-card',
        type: 'block',
        blockType: 'GlassCardSurface',
        title: 'Tarjeta Glass Requisitos',
        position: { x: 50, y: 68 },
        zIndex: 20,
        scale: 1,
        width: 920,
        height: 160,
        props: {
          variant: 'teal',
          blur: 'backdrop-blur-md',
          borderOpacity: 'border-teal-500/30',
        },
      },
      {
        id: 'layer-glass-text',
        type: 'text',
        title: 'Checklist 4 Requisitos',
        position: { x: 50, y: 68 },
        zIndex: 22,
        scale: 1,
        width: 860,
        props: {
          text: '✓ 0€ Copagos   ·   ✓ 0 Días Carencia   ·   ✓ Repatriación 100%   ·   ✓ Sanitas Students',
          tag: 'p',
          fontWeight: '700',
          fontSize: 20,
          color: '#94D2BD',
          textAlign: 'center',
        },
      },
      {
        id: 'layer-trust-verified',
        type: 'block',
        blockType: 'TrustVerifiedPill',
        title: 'Sello Homologación Consular',
        position: { x: 50, y: 81 },
        zIndex: 25,
        scale: 1,
        width: 480,
        height: 44,
        props: {
          verifiedLabel: '100% HOMOLOGADO PARA CONSULADOS Y EXTRANJERÍA',
        },
      },
      {
        id: 'layer-cta-whatsapp',
        type: 'block',
        blockType: 'WhatsAppCtaButton',
        title: 'Botón CTA Asesoría WhatsApp',
        position: { x: 50, y: 91 },
        zIndex: 30,
        scale: 1,
        width: 460,
        height: 56,
        props: {
          ctaText: '💬 Asesoría Gratuita con Lucía Delgado',
          phoneNumber: '+34600000000',
          primaryColor: '#EE9B00',
          accentColor: '#005F73',
          textColor: '#001219',
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 📱 2. DISEÑO OFICIAL TIKTOK & STORIES (9:16)
  {
    id: 'template-student-visa-tiktok',
    title: 'TikTok & Reel: Guía Visado Estudiante 2026 (9:16)',
    preset: IMAGE_FORMAT_PRESETS[1], // 9:16 (1080x1920)
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 12%, rgba(0, 95, 115, 0.85) 0%, #001219 90%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-tiktok-highlight',
        type: 'block',
        blockType: 'TrustHighlightPill',
        title: 'Sello Garantía Consular',
        position: { x: 50, y: 9 },
        zIndex: 10,
        scale: 1,
        width: 320,
        height: 42,
        props: {
          highlight: 'GARANTÍA CONSULAR 100%',
        },
      },
      {
        id: 'layer-tiktok-hook',
        type: 'text',
        title: 'Pregunta Gancho',
        position: { x: 50, y: 17 },
        zIndex: 12,
        scale: 1,
        width: 900,
        props: {
          text: '¿Vas a estudiar en España este año?',
          tag: 'h1',
          fontWeight: '900',
          fontSize: 40,
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1.2,
        },
      },
      {
        id: 'layer-tiktok-subtitle',
        type: 'text',
        title: 'Subtítulo Explicativo',
        position: { x: 50, y: 24 },
        zIndex: 14,
        scale: 1,
        width: 880,
        props: {
          text: 'Las 4 condiciones obligatorias que exige Extranjería para tu seguro médico',
          tag: 'h2',
          fontWeight: '600',
          fontSize: 22,
          color: '#94D2BD',
          textAlign: 'center',
          lineHeight: 1.3,
        },
      },
      {
        id: 'layer-tiktok-illustration',
        type: 'block',
        blockType: 'WebIllustration',
        title: 'Ilustración Estudiante',
        position: { x: 50, y: 41 },
        zIndex: 16,
        scale: 1,
        width: 440,
        height: 310,
        props: {
          illustrationId: 'student',
          title: 'Estudiantes & Visados',
          colorPrimary: '#005F73',
          colorPastel: '#94D2BD',
          colorSecondary: '#FFFFFF',
          colorAccent: '#EE9B00',
          colorNeutral: '#1e293b',
        },
      },
      {
        id: 'layer-tiktok-glass',
        type: 'block',
        blockType: 'GlassCardSurface',
        title: 'Superficie Glass Ámbar',
        position: { x: 50, y: 62 },
        zIndex: 20,
        scale: 1,
        width: 920,
        height: 240,
        props: {
          variant: 'amber',
          blur: 'backdrop-blur-md',
          borderOpacity: 'border-amber-500/30',
        },
      },
      {
        id: 'layer-tiktok-items',
        type: 'text',
        title: 'Lista de 4 Requisitos',
        position: { x: 50, y: 62 },
        zIndex: 22,
        scale: 1,
        width: 860,
        props: {
          text: '1. Sin Copagos (0€ adicionales)\n2. Sin Carencias (Válido desde el día 1)\n3. Cobertura Sanidad Pública Completa\n4. Repatriación Sanitaria y de Restos',
          tag: 'p',
          fontWeight: '700',
          fontSize: 21,
          color: '#FFFFFF',
          textAlign: 'center',
          lineHeight: 1.6,
        },
      },
      {
        id: 'layer-tiktok-advisor',
        type: 'block',
        blockType: 'HookAlertBadge',
        title: 'Insignia Asesora Asignada',
        position: { x: 50, y: 77 },
        zIndex: 25,
        scale: 1,
        width: 380,
        height: 44,
        props: {
          badge: 'ASESORA ASIGNADA · LUCÍA DELGADO',
          pulseColor: '#94D2BD',
        },
      },
      {
        id: 'layer-tiktok-cta',
        type: 'block',
        blockType: 'WhatsAppCtaButton',
        title: 'Botón CTA Sanitas Students',
        position: { x: 50, y: 88 },
        zIndex: 30,
        scale: 1,
        width: 480,
        height: 60,
        props: {
          ctaText: '👉 Cotizar Sanitas Students en 1 Minuto',
          phoneNumber: '+34600000000',
          primaryColor: '#25D366',
          accentColor: '#FFFFFF',
          textColor: '#FFFFFF',
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 3. PLANTILLAS BASE
  {
    id: 'template-advisor-portrait',
    title: 'Post Asesora de Visados (4:5)',
    preset: IMAGE_FORMAT_PRESETS[0], // 4:5
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 20%, rgba(0, 95, 115, 0.75) 0%, #001219 80%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-advisor-main',
        type: 'block',
        blockType: 'MotionAdvisorCard',
        title: 'Tarjeta de Asesora',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        props: {
          name: 'Sofía',
          role: 'Asesora Especialista en Visados',
          badge: 'ASESORA ASIGNADA · EN DIRECTO',
          message: 'Te ayudo a verificar que tu póliza cumple el 100% de los requisitos del consulado sin copagos.',
          avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=256&auto=format&fit=crop',
          whatsAppText: 'Pregúntanos por WhatsApp',
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-trust-square',
    title: 'Garantía Consular 100% (1:1)',
    preset: IMAGE_FORMAT_PRESETS[2], // 1:1
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 30%, rgba(238, 155, 0, 0.45) 0%, #001219 75%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-trust-main',
        type: 'block',
        blockType: 'MotionTrustBadge',
        title: 'Sello de Garantía',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        props: {
          title: 'PÓLIZA 100% VÁLIDA PARA VISADO',
          subtitle: 'Sin Copagos · Cobertura Completa · Repatriación Incluida',
          highlight: 'GARANTÍA CONSULAR',
          verifiedLabel: 'VERIFICADO PARA EXTRANJERÍA',
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-comparison-portrait',
    title: 'Comparativa Seguro Viaje vs Visado (4:5)',
    preset: IMAGE_FORMAT_PRESETS[0], // 4:5
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 25%, rgba(0, 95, 115, 0.6) 0%, #001219 85%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-comp-main',
        type: 'block',
        blockType: 'MotionComparisonCard',
        title: 'Comparativa Visual',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        props: {
          title: '¿SEGURO DE VIAJE O SEGURO DE VISADO?',
          wrongOptionTitle: 'Seguro de Viaje Común',
          wrongOptionDesc: 'Denegación de visado: no cumple requisitos consulares ni incluye red médica completa.',
          correctOptionTitle: 'Seguro VitaBlue Extranjería',
          correctOptionDesc: 'Aprobación garantizada: sin copagos, cobertura total y repatriación incluida.',
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-providers-square',
    title: 'Parrilla Aseguradoras Aprobadas (1:1)',
    preset: IMAGE_FORMAT_PRESETS[2], // 1:1
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 20%, rgba(148, 210, 189, 0.4) 0%, #001219 80%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-providers-main',
        type: 'block',
        blockType: 'MotionProviderGrid',
        title: 'Grid de Aseguradoras',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        props: {
          title: 'COMPAÑÍAS LÍDERES AUTORIZADAS',
          subtitle: 'Aceptadas oficialmente por Extranjería y Consulados',
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 🌟 5. DESTACADOS DE INSTAGRAM OFICIALES (PORTADAS CIRCULARES 1:1)
  {
    id: 'template-highlight-approved',
    title: 'Destacado Instagram: Aprobados (1:1)',
    preset: IMAGE_FORMAT_PRESETS[2], // 1:1 (1080x1080)
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 35%, rgba(0, 95, 115, 0.85) 0%, #001219 80%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-highlight-approved',
        type: 'block',
        blockType: 'InstagramHighlightBadge',
        title: 'Portada Destacado Aprobados',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        width: 820,
        height: 820,
        props: {
          iconKey: 'approved',
          label: 'Aprobados',
          showLabel: false,
          ringColor: '#EE9B00',
          glowColor: 'rgba(238, 155, 0, 0.55)',
          strokeColor: '#FFFFFF',
          accentColor: '#EE9B00',
          isFullCover: true,
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-highlight-visa',
    title: 'Destacado Instagram: Visados (1:1)',
    preset: IMAGE_FORMAT_PRESETS[2], // 1:1 (1080x1080)
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 35%, rgba(0, 95, 115, 0.85) 0%, #001219 80%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-highlight-visa',
        type: 'block',
        blockType: 'InstagramHighlightBadge',
        title: 'Portada Destacado Visados',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        width: 820,
        height: 820,
        props: {
          iconKey: 'visa',
          label: 'Visados',
          showLabel: false,
          ringColor: '#94D2BD',
          glowColor: 'rgba(148, 210, 189, 0.55)',
          strokeColor: '#FFFFFF',
          accentColor: '#94D2BD',
          isFullCover: true,
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-highlight-process',
    title: 'Destacado Instagram: Paso a Paso (1:1)',
    preset: IMAGE_FORMAT_PRESETS[2], // 1:1 (1080x1080)
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 35%, rgba(0, 95, 115, 0.85) 0%, #001219 80%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-highlight-process',
        type: 'block',
        blockType: 'InstagramHighlightBadge',
        title: 'Portada Destacado Proceso',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        width: 820,
        height: 820,
        props: {
          iconKey: 'process',
          label: 'Paso a Paso',
          showLabel: false,
          ringColor: '#EE9B00',
          glowColor: 'rgba(238, 155, 0, 0.55)',
          strokeColor: '#FFFFFF',
          accentColor: '#EE9B00',
          isFullCover: true,
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-highlight-faq',
    title: 'Destacado Instagram: Dudas & FAQ (1:1)',
    preset: IMAGE_FORMAT_PRESETS[2], // 1:1 (1080x1080)
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 35%, rgba(0, 95, 115, 0.85) 0%, #001219 80%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-highlight-faq',
        type: 'block',
        blockType: 'InstagramHighlightBadge',
        title: 'Portada Destacado FAQ',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        width: 820,
        height: 820,
        props: {
          iconKey: 'faq',
          label: 'Dudas & FAQ',
          showLabel: false,
          ringColor: '#94D2BD',
          glowColor: 'rgba(148, 210, 189, 0.55)',
          strokeColor: '#FFFFFF',
          accentColor: '#94D2BD',
          isFullCover: true,
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-highlight-contact',
    title: 'Destacado Instagram: Contacto WhatsApp (1:1)',
    preset: IMAGE_FORMAT_PRESETS[2], // 1:1 (1080x1080)
    background: {
      type: 'mesh',
      gradient: 'radial-gradient(circle at 50% 35%, rgba(0, 95, 115, 0.85) 0%, #001219 80%)',
      color: '#001219',
    },
    brandTokens: defaultMotionBrandTokens,
    layers: [
      {
        id: 'layer-highlight-contact',
        type: 'block',
        blockType: 'InstagramHighlightBadge',
        title: 'Portada Destacado Contacto',
        position: { x: 50, y: 50 },
        zIndex: 10,
        scale: 1,
        width: 820,
        height: 820,
        props: {
          iconKey: 'contact',
          label: 'Contacto WhatsApp',
          showLabel: false,
          ringColor: '#EE9B00',
          glowColor: 'rgba(238, 155, 0, 0.55)',
          strokeColor: '#FFFFFF',
          accentColor: '#EE9B00',
          isFullCover: true,
        },
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
